
package com.evry.restaurantservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IRestaurantServiceImplService", targetNamespace = "http://www.evry.com/RestaurantService/", wsdlLocation = "file:/C:/Users/srinivasa.nayana/evry/apachecfx-soap-contractfirst-latest/src/main/webapp/WEB-INF/RestaurantService.wsdl")
public class IRestaurantServiceImplService
    extends Service
{

    private final static URL IRESTAURANTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IRESTAURANTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName IRESTAURANTSERVICEIMPLSERVICE_QNAME = new QName("http://www.evry.com/RestaurantService/", "IRestaurantServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/srinivasa.nayana/evry/apachecfx-soap-contractfirst-latest/src/main/webapp/WEB-INF/RestaurantService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IRESTAURANTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        IRESTAURANTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IRestaurantServiceImplService() {
        super(__getWsdlLocation(), IRESTAURANTSERVICEIMPLSERVICE_QNAME);
    }

    public IRestaurantServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IRESTAURANTSERVICEIMPLSERVICE_QNAME, features);
    }

    public IRestaurantServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, IRESTAURANTSERVICEIMPLSERVICE_QNAME);
    }

    public IRestaurantServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IRESTAURANTSERVICEIMPLSERVICE_QNAME, features);
    }

    public IRestaurantServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IRestaurantServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRestaurantService
     */
    @WebEndpoint(name = "IRestaurantServiceImplPort")
    public IRestaurantService getIRestaurantServiceImplPort() {
        return super.getPort(new QName("http://www.evry.com/RestaurantService/", "IRestaurantServiceImplPort"), IRestaurantService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRestaurantService
     */
    @WebEndpoint(name = "IRestaurantServiceImplPort")
    public IRestaurantService getIRestaurantServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.evry.com/RestaurantService/", "IRestaurantServiceImplPort"), IRestaurantService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IRESTAURANTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw IRESTAURANTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return IRESTAURANTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
