
package com.evry.restaurantservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRestaurantService", targetNamespace = "http://www.evry.com/RestaurantService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRestaurantService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.restaurantservice.AddRestaurantResponse
     */
    @WebMethod
    @WebResult(name = "AddRestaurantResponse", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
    public AddRestaurantResponse addRestaurant(
        @WebParam(name = "AddRestaurantRequest", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
        AddRestaurantRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.restaurantservice.GetRestaurantListResponse
     */
    @WebMethod
    @WebResult(name = "GetRestaurantListResponse", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
    public GetRestaurantListResponse getRestaurantList(
        @WebParam(name = "GetRestaurantListRequest", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
        GetRestaurantListRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.restaurantservice.AddMenuResponse
     */
    @WebMethod
    @WebResult(name = "AddMenuResponse", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
    public AddMenuResponse addMenu(
        @WebParam(name = "AddMenuRequest", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
        AddMenuRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.restaurantservice.DeleteMenuResponse
     */
    @WebMethod
    @WebResult(name = "DeleteMenuResponse", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
    public DeleteMenuResponse deleteMenu(
        @WebParam(name = "DeleteMenuRequest", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
        DeleteMenuRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.evry.restaurantservice.GetMenuListResponse
     */
    @WebMethod
    @WebResult(name = "GetMenuListResponse", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
    public GetMenuListResponse getMenuList(
        @WebParam(name = "GetMenuListRequest", targetNamespace = "http://www.evry.com/RestaurantService/", partName = "parameters")
        GetMenuListRequest parameters);

}
